export { default as cover_security } from "./cover_security.png"
export { default as cover_vps } from "./cover_vps.png"
export { default as cover_mob } from "../software/cover_mob.png"
export { default as shape_1 } from "./1.png"
export { default as shape_2 } from "./2.png"
export { default as shape_3 } from "./3.png"
